create table if not exists public.store_customer_profiles (
  id bigint generated by default as identity primary key,
  auth_user_id uuid not null unique references auth.users (id) on delete cascade,
  nombre text not null default '',
  apellido text not null default '',
  celular text not null default '',
  ciudad text not null default '',
  correo text not null default '',
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists idx_store_customer_profiles_auth_user_id
  on public.store_customer_profiles (auth_user_id);

drop trigger if exists trg_store_customer_profiles_updated_at on public.store_customer_profiles;

create trigger trg_store_customer_profiles_updated_at
before update on public.store_customer_profiles
for each row
execute function public.set_updated_at();

create or replace function public.sync_store_customer_profile_from_auth_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  meta jsonb;
begin
  meta := coalesce(new.raw_user_meta_data, '{}'::jsonb);

  insert into public.store_customer_profiles (
    auth_user_id,
    nombre,
    apellido,
    celular,
    ciudad,
    correo
  )
  values (
    new.id,
    coalesce(meta ->> 'first_name', ''),
    coalesce(meta ->> 'last_name', ''),
    coalesce(meta ->> 'phone', ''),
    coalesce(meta ->> 'city', ''),
    coalesce(new.email, '')
  )
  on conflict (auth_user_id) do update
  set
    nombre = excluded.nombre,
    apellido = excluded.apellido,
    celular = excluded.celular,
    ciudad = excluded.ciudad,
    correo = excluded.correo,
    updated_at = timezone('utc', now());

  return new;
end;
$$;

drop trigger if exists on_auth_user_store_customer_profile on auth.users;

create trigger on_auth_user_store_customer_profile
after insert or update of email, raw_user_meta_data
on auth.users
for each row
execute function public.sync_store_customer_profile_from_auth_user();

insert into public.store_customer_profiles (
  auth_user_id,
  nombre,
  apellido,
  celular,
  ciudad,
  correo
)
select
  u.id,
  coalesce(u.raw_user_meta_data ->> 'first_name', ''),
  coalesce(u.raw_user_meta_data ->> 'last_name', ''),
  coalesce(u.raw_user_meta_data ->> 'phone', ''),
  coalesce(u.raw_user_meta_data ->> 'city', ''),
  coalesce(u.email, '')
from auth.users u
on conflict (auth_user_id) do update
set
  nombre = excluded.nombre,
  apellido = excluded.apellido,
  celular = excluded.celular,
  ciudad = excluded.ciudad,
  correo = excluded.correo,
  updated_at = timezone('utc', now());

alter table public.store_customer_profiles enable row level security;

drop policy if exists "store_customer_profiles_select_own" on public.store_customer_profiles;
create policy "store_customer_profiles_select_own"
on public.store_customer_profiles
for select
to authenticated
using (auth.uid() = auth_user_id);

drop policy if exists "store_customer_profiles_update_own" on public.store_customer_profiles;
create policy "store_customer_profiles_update_own"
on public.store_customer_profiles
for update
to authenticated
using (auth.uid() = auth_user_id)
with check (auth.uid() = auth_user_id);
