create table if not exists public.store_customer_addresses (
  id bigint generated by default as identity primary key,
  auth_user_id uuid not null references auth.users (id) on delete cascade,
  etiqueta text not null default 'Principal',
  destinatario text not null default '',
  telefono text not null default '',
  ciudad text not null default '',
  direccion text not null default '',
  referencia text not null default '',
  is_default boolean not null default false,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists idx_store_customer_addresses_auth_user_id
  on public.store_customer_addresses (auth_user_id, created_at desc);

drop trigger if exists trg_store_customer_addresses_updated_at on public.store_customer_addresses;

create trigger trg_store_customer_addresses_updated_at
before update on public.store_customer_addresses
for each row
execute function public.set_updated_at();

create unique index if not exists idx_store_customer_addresses_single_default
  on public.store_customer_addresses (auth_user_id)
  where is_default = true;

create table if not exists public.store_customer_favorites (
  id bigint generated by default as identity primary key,
  auth_user_id uuid not null references auth.users (id) on delete cascade,
  product_id bigint not null references public.productos (id) on delete cascade,
  created_at timestamptz not null default timezone('utc', now()),
  unique (auth_user_id, product_id)
);

create index if not exists idx_store_customer_favorites_auth_user_id
  on public.store_customer_favorites (auth_user_id, created_at desc);

create index if not exists idx_store_customer_favorites_product_id
  on public.store_customer_favorites (product_id);

create table if not exists public.store_product_reviews (
  id bigint generated by default as identity primary key,
  auth_user_id uuid not null references auth.users (id) on delete cascade,
  product_id bigint not null references public.productos (id) on delete cascade,
  nombre_mostrado text not null default '',
  rating integer not null check (rating between 1 and 5),
  comentario text not null default '',
  status text not null default 'publicado' check (status in ('publicado', 'oculto')),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists idx_store_product_reviews_product_id
  on public.store_product_reviews (product_id, created_at desc);

create index if not exists idx_store_product_reviews_auth_user_id
  on public.store_product_reviews (auth_user_id, created_at desc);

drop trigger if exists trg_store_product_reviews_updated_at on public.store_product_reviews;

create trigger trg_store_product_reviews_updated_at
before update on public.store_product_reviews
for each row
execute function public.set_updated_at();

create table if not exists public.store_customer_notification_preferences (
  id bigint generated by default as identity primary key,
  auth_user_id uuid not null unique references auth.users (id) on delete cascade,
  email_order_received boolean not null default true,
  email_payment_review boolean not null default true,
  email_payment_confirmed boolean not null default true,
  email_order_sent boolean not null default true,
  email_order_delivered boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

drop trigger if exists trg_store_customer_notification_preferences_updated_at on public.store_customer_notification_preferences;

create trigger trg_store_customer_notification_preferences_updated_at
before update on public.store_customer_notification_preferences
for each row
execute function public.set_updated_at();

create table if not exists public.store_email_notification_queue (
  id bigint generated by default as identity primary key,
  auth_user_id uuid references auth.users (id) on delete set null,
  pedido_web_id bigint references public.pedidos_web (id) on delete set null,
  event_type text not null,
  recipient_email text not null default '',
  payload jsonb not null default '{}'::jsonb,
  status text not null default 'pending' check (status in ('pending', 'processed', 'failed')),
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists idx_store_email_notification_queue_status
  on public.store_email_notification_queue (status, created_at asc);

alter table public.store_customer_addresses enable row level security;
alter table public.store_customer_favorites enable row level security;
alter table public.store_product_reviews enable row level security;
alter table public.store_customer_notification_preferences enable row level security;

drop policy if exists "store_customer_addresses_select_own" on public.store_customer_addresses;
create policy "store_customer_addresses_select_own"
on public.store_customer_addresses
for select
to authenticated
using (auth.uid() = auth_user_id);

drop policy if exists "store_customer_addresses_insert_own" on public.store_customer_addresses;
create policy "store_customer_addresses_insert_own"
on public.store_customer_addresses
for insert
to authenticated
with check (auth.uid() = auth_user_id);

drop policy if exists "store_customer_addresses_update_own" on public.store_customer_addresses;
create policy "store_customer_addresses_update_own"
on public.store_customer_addresses
for update
to authenticated
using (auth.uid() = auth_user_id)
with check (auth.uid() = auth_user_id);

drop policy if exists "store_customer_addresses_delete_own" on public.store_customer_addresses;
create policy "store_customer_addresses_delete_own"
on public.store_customer_addresses
for delete
to authenticated
using (auth.uid() = auth_user_id);

drop policy if exists "store_customer_favorites_select_own" on public.store_customer_favorites;
create policy "store_customer_favorites_select_own"
on public.store_customer_favorites
for select
to authenticated
using (auth.uid() = auth_user_id);

drop policy if exists "store_customer_favorites_insert_own" on public.store_customer_favorites;
create policy "store_customer_favorites_insert_own"
on public.store_customer_favorites
for insert
to authenticated
with check (auth.uid() = auth_user_id);

drop policy if exists "store_customer_favorites_delete_own" on public.store_customer_favorites;
create policy "store_customer_favorites_delete_own"
on public.store_customer_favorites
for delete
to authenticated
using (auth.uid() = auth_user_id);

drop policy if exists "store_product_reviews_select_public" on public.store_product_reviews;
create policy "store_product_reviews_select_public"
on public.store_product_reviews
for select
to authenticated, anon
using (status = 'publicado');

drop policy if exists "store_product_reviews_insert_own" on public.store_product_reviews;
create policy "store_product_reviews_insert_own"
on public.store_product_reviews
for insert
to authenticated
with check (auth.uid() = auth_user_id);

drop policy if exists "store_product_reviews_update_own" on public.store_product_reviews;
create policy "store_product_reviews_update_own"
on public.store_product_reviews
for update
to authenticated
using (auth.uid() = auth_user_id)
with check (auth.uid() = auth_user_id);

drop policy if exists "store_customer_notification_preferences_select_own" on public.store_customer_notification_preferences;
create policy "store_customer_notification_preferences_select_own"
on public.store_customer_notification_preferences
for select
to authenticated
using (auth.uid() = auth_user_id);

drop policy if exists "store_customer_notification_preferences_insert_own" on public.store_customer_notification_preferences;
create policy "store_customer_notification_preferences_insert_own"
on public.store_customer_notification_preferences
for insert
to authenticated
with check (auth.uid() = auth_user_id);

drop policy if exists "store_customer_notification_preferences_update_own" on public.store_customer_notification_preferences;
create policy "store_customer_notification_preferences_update_own"
on public.store_customer_notification_preferences
for update
to authenticated
using (auth.uid() = auth_user_id)
with check (auth.uid() = auth_user_id);

insert into public.store_customer_notification_preferences (auth_user_id)
select id
from auth.users
on conflict (auth_user_id) do nothing;
