create table if not exists public.pedidos_web (
  id bigint generated by default as identity primary key,
  codigo text unique,
  estado text not null default 'pendiente',
  estado_pago text not null default 'pendiente',
  metodo_pago text not null,
  cliente_nombre text not null,
  cliente_telefono text not null,
  cliente_correo text not null,
  cliente_ciudad text not null,
  subtotal numeric(12, 2) not null default 0,
  total numeric(12, 2) not null default 0,
  origen text not null default 'ventra-store',
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint pedidos_web_metodo_pago_check
    check (metodo_pago in ('qr', 'transferencia', 'efectivo')),
  constraint pedidos_web_estado_check
    check (estado in ('pendiente', 'confirmado', 'cancelado', 'completado')),
  constraint pedidos_web_estado_pago_check
    check (estado_pago in ('pendiente', 'por_confirmar', 'pagado', 'rechazado'))
);

create table if not exists public.pedido_web_items (
  id bigint generated by default as identity primary key,
  pedido_web_id bigint not null references public.pedidos_web (id) on delete cascade,
  producto_id bigint references public.productos (id) on delete set null,
  producto_nombre text not null,
  producto_sku text,
  cantidad integer not null,
  precio_unitario numeric(12, 2) not null,
  subtotal numeric(12, 2) not null,
  created_at timestamptz not null default timezone('utc', now()),
  constraint pedido_web_items_cantidad_check check (cantidad > 0)
);

create index if not exists idx_pedidos_web_estado_created_at
  on public.pedidos_web (estado, created_at desc);

create index if not exists idx_pedidos_web_estado_pago_created_at
  on public.pedidos_web (estado_pago, created_at desc);

create index if not exists idx_pedido_web_items_pedido_web_id
  on public.pedido_web_items (pedido_web_id);

drop trigger if exists trg_pedidos_web_updated_at on public.pedidos_web;

create trigger trg_pedidos_web_updated_at
before update on public.pedidos_web
for each row
execute function public.set_updated_at();
